# Generated by Django 3.2.23 on 2023-12-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20190716_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
